version: '3.3'

services:
  database:
    image: mysql:8.0
    container_name: notifications_database
    restart: always
    ports:
      - '3306:3306'
    environment:
      - MYSQL_DATABASE=notifications
      - MYSQL_ROOT_PASSWORD=Biel.borel22
    volumes:
      - db:/var/lib/mysql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql

  app:
    build:
      context: .
    container_name: notifications_app
    env_file:
      - .env
    ports:
      - '3000:3000'
    volumes:
      - .:/usr/app
    links:
      - database
    depends_on:
      - database

volumes:
  db:
    driver: local
